name: Mkdocs and Github Actions

on:
  push:
    branches:
      - mkdocs
    paths:
      - 'docs/**'
      - 'docs/mkdocs.yml'
      - '.github/workflows/deploy.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Python dependencies
        run: pip install -r docs/requirements.txt

      - name: Build MkDocs site
        run: mkdocs build -f docs/mkdocs.yml

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Deploy to Vercel (Production)
        run: vercel --prod --token=$VERCEL_TOKEN --confirm --cwd ./docs/site
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
